//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetris.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tetris.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000000000000000
        ///0010000000000100
        ///0010000000000100
        ///0010000000000100
        ///0010000000000100
        ///0010000000000100
        ///0010000000000100
        ///0010000000000100
        ///0010000000000100
        ///0010000000000100
        ///0010000000000100
        ///0010000000000100
        ///0010000000000100
        ///0010000000000100
        ///0010000000000100
        ///0010000000000100
        ///0011111111111100
        ///0000000000000000.
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0111101111101101101111
        ///0100001000101101101000
        ///0100001000101010101111
        ///0100101111101000101000
        ///0111101000101000101111
        ///0000000000000000000000
        ///0111110100010111101111
        ///0100010100010100001001
        ///0100010010100111101001
        ///0100010010100100001110
        ///0111110001000111101001.
        /// </summary>
        public static string GameOver {
            get {
                return ResourceManager.GetString("GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0110
        ///0100
        ///0100
        ///0000
        ///0000
        ///1110
        ///0010
        ///0000
        ///0100
        ///0100
        ///1100
        ///0000
        ///1000
        ///1110
        ///0000
        ///0000.
        /// </summary>
        public static string JShape {
            get {
                return ResourceManager.GetString("JShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0100
        ///0100
        ///0100
        ///0100
        ///0000
        ///1111
        ///0000
        ///0000
        ///0010
        ///0010
        ///0010
        ///0010
        ///0000
        ///0000
        ///1111
        ///0000.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1100
        ///0100
        ///0100
        ///0000
        ///0010
        ///1110
        ///0000
        ///0000
        ///0100
        ///0100
        ///0110
        ///0000
        ///0000
        ///1110
        ///1000
        ///0000.
        /// </summary>
        public static string LShape {
            get {
                return ResourceManager.GetString("LShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream Music {
            get {
                return ResourceManager.GetStream("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000
        ///0110
        ///0110
        ///0000.
        /// </summary>
        public static string Square {
            get {
                return ResourceManager.GetString("Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000
        ///1100
        ///0100
        ///0000
        ///0110
        ///1100
        ///0000
        ///0000
        ///0100
        ///0110
        ///0010
        ///0000
        ///0000
        ///0110
        ///1100
        ///0000.
        /// </summary>
        public static string SShape {
            get {
                return ResourceManager.GetString("SShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0100
        ///1110
        ///0000
        ///0000
        ///0100
        ///0110
        ///0100
        ///0000
        ///0000
        ///1110
        ///0100
        ///0000
        ///0100
        ///1100
        ///0100
        ///0000.
        /// </summary>
        public static string Tee {
            get {
                return ResourceManager.GetString("Tee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0100
        ///1100
        ///1000
        ///0000
        ///1100
        ///0110
        ///0000
        ///0000
        ///0010
        ///0110
        ///0100
        ///0000
        ///0000
        ///1100
        ///0110
        ///0000.
        /// </summary>
        public static string ZShape {
            get {
                return ResourceManager.GetString("ZShape", resourceCulture);
            }
        }
    }
}
